"""Erzeugt Item-Texturen (Waffen, Messer, Munition, Gegenmittel, Spawn-Eier), Effekt-Icon und Mod-Icon.

Aufruf: python3 tools/gen_items.py  (aus dem deadzone-Ordner)
"""
import os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..", "src", "main", "resources", "assets", "deadzone")
ITEM_DIR = os.path.join(ROOT, "textures", "item")
EFFECT_DIR = os.path.join(ROOT, "textures", "mob_effect")
PREVIEW = os.environ.get("PREVIEW_DIR")

PALETTE = {
    ".": None,
    "K": "#17181c", "D": "#33363d", "M": "#555a64", "L": "#8a909c", "H": "#c4c9d2",
    "W": "#4e3018", "w": "#7d5129", "v": "#a06a38",
    "G": "#3d4a22", "g": "#5c6e30",
    "T": "#8a7650", "t": "#b39d6c",
    "Y": "#d1a93a", "y": "#8e6e1e",
    "R": "#9c2020", "r": "#d04a3a",
    "B": "#22262e", "O": "#c86a1a", "S": "#4a8ac0",
    "E": "#3cdc3c", "e": "#a8ff8a", "Q": "#1e7a1e",
}


def hexc(h):
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), 255)


def draw(rows, size=16):
    assert len(rows) == size, (len(rows), rows)
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        assert len(row) == size, (y, row, len(row))
        for x, ch in enumerate(row):
            c = PALETTE[ch]
            if c:
                img.putpixel((x, y), hexc(c))
    return img


ART = {}

ART["pistol_m9"] = """
................
................
................
................
................
...KKKKKKKKKKK..
...KHLLLLLLLLLK.
...KMMMMMMMMMMK.
...KKDDKKKKKKKK.
....KDDKDK......
....KDDKK.......
...KDDDK........
...KDDDK........
...KBBBK........
...KKKKK........
................
"""

ART["revolver"] = """
................
................
................
................
................
.....KKK........
....KLLLKKKKKKKK
...KKMHMMLLLLLLK
...KDMMMMMMMMMMK
...KKKDDKKKKKKKK
.....KWDK.K.....
....KWwKKK......
....KWwK........
...KWwvK........
...KWWWK........
...KKKKK........
"""

ART["desert_eagle"] = """
................
................
................
................
..KKKKKKKKKKKKK.
..KHHHHHHHHHHHHK
..KLLLLLLLLLLLLK
..KMMMMMMMMMMMMK
..KKKLLKKKKKKKKK
...KLLLKDK......
...KLLLKK.......
..KMLLLK........
..KMLLLK........
..KDDDDK........
..KKKKKK........
................
"""

ART["uzi"] = """
................
................
................
................
..KKKKKKKKKKK...
.KDDDDDDDDDDDKKK
.KMMMMMMMMMMMMMK
.KDDDDDDDDDDDKKK
.KKKKKDDDKKKKK..
.....KDDDK.K....
.....KBBBKK.....
.....KBBBK......
.....KBBBK......
.....KBBBK......
.....KKKKK......
................
"""

ART["mp5"] = """
................
................
................
................
.....KKKKKKKKK..
KK..KDDDDDDDDDKK
KDKKKMMMMMMMMMMK
KDDDDDDDDDDDDDKK
KDKKKKDKKBKKKK..
KK...KDK.KBK....
.....KDK..KBK...
.....KKK...KBK..
............KK..
................
................
................
"""

ART["p90"] = """
................
................
................
................
...KKKKKKKKKKK..
..KGGgggggggGGK.
.KGGGGGGGGGGGGGK
.KGBBBBBBBBBBBBK
.KGGKKGKKKKGGGK.
..KGK.GGK..KKK..
..KKK.KGK.......
.......KK.......
................
................
................
................
"""

ART["ak47"] = """
................
................
................
................
................
KK....KKKKKKKKKK
KwKKKKDDDDDDDDDK
KwwwwKMMMMwwwwKK
KWwwwKDDDDWWWK..
KKWWKKKDKBBKK...
..KK..KDK.KBK...
......KKK..KBK..
............KBK.
.............KK.
................
................
"""

ART["m4a1"] = """
................
................
................
................
......KKKK......
KK...KBDDBK.....
KBKKKKBBBBKKKKKK
KBBBBBBBBBBBBBBK
KBBBKKBKKBBKKKK.
KKKK.KBK.KBK....
.....KBK.KBK....
.....KKK.KBK....
.........KKK....
................
................
................
"""

ART["scar"] = """
................
................
................
................
.....KKKKKKK....
KK..KTTTTTTTK...
KTKKKtttttttKKKK
KTTTTTTTTTTTTTTK
KTTKKKTKKTTKKKK.
KKKK.KTK.KTK....
.....KTK.KTK....
.....KKK.KKK....
................
................
................
................
"""

ART["dmr"] = """
................
................
................
.....KKKKKK.....
....KDSDDDSK....
.....KKDDKK.....
KK...KKKKKKKKKKK
KWKKKDDDDDDDDDDK
KWWWWMMMMMMMMMMK
KWWWKDDDDKKKKKK.
KKKKKKDKKBK.....
.....KDK.KBK....
.....KKK..KK....
................
................
................
"""

ART["pump_shotgun"] = """
................
................
................
................
................
KK..............
KwKKKKKKKKKKKKKK
KwwwKDDDDDDDDDDK
KWwwKMMMMMMMMMMK
KWWKKKDKKvvvvvKK
KKK..KDK.KwwwK..
.....KKK..KKK...
................
................
................
................
"""

ART["double_barrel"] = """
................
................
................
................
................
KKK.............
KvwKKKKKKKKKKKKK
KwwwwKLLLLLLLLLK
KWwwwKMMMMMMMMMK
KWWWKKLLLLLLLLLK
KKKKKDKKKKKKKKKK
....KDK.........
....KKK.........
................
................
................
"""

ART["auto_shotgun"] = """
................
................
................
................
.....KKKKKKKKK..
KK..KBBBBBBBBBKK
KBKKKMMMMMMMMMMK
KBBBBBBBBBBBBBKK
KBBKKKBKKKKKKK..
KKK..KBKKDDDK...
.....KBKKDMDK...
.....KKKKDDDK...
........KKKKK...
................
................
................
"""

ART["hunting_rifle"] = """
................
................
................
.....KKKKKKK....
....KDSDDDDSK...
.....KKKDKK.....
KKK..KKKKKKKKKKK
KvwKKwwwwwwDDDDK
KwwwwwwwwwwMMMMK
KWWWKKWWWWWKKKKK
KKKKKKDK........
.....KKK........
................
................
................
................
"""

ART["sniper_rifle"] = """
................
................
....KKKKKKKK....
...KDSDDDDDSK...
....KKKDDKKK....
KK....KKKKKKKKKK
KGKKKKGGGGGDDDDK
KGGGGgggggggMMMK
KGGGKKGGGKKKKKKK
KKKKKKGK..KK....
.....KKK.K..K...
........K....K..
................
................
................
................
"""

ART["barrett"] = """
................
................
....KKKKKKKK....
...KBSBBBBBSK...
....KKKBBKKK....
KK..KKKKKKKKKKKK
KBKKKBBBBBBBDDKK
KBBBBBBBBBBBMMLK
KBBBKKBKKBBKKDKK
KKKKKKBKKBBK.KK.
.....KBKKBBK....
.....KKK.KKK....
................
................
................
................
"""

ART["m249"] = """
................
................
................
................
.....KKKKKKK....
KK..KBBBBBBBK...
KBKKKBBBBBBBKKKK
KBBBBBBBBBBBBBBK
KBBBKKKBKKKKKKKK
KKKK.KBBBBK.K.K.
.....KGGGGK.K..K
.....KGggGK.....
.....KGGGGK.....
.....KKKKKK.....
................
................
"""

ART["minigun"] = """
................
................
................
....KKKK........
...KDDDDKKKKKKKK
..KDMMMMLLLLLLLK
.KDDDDDDMMMMMMMK
.KDMMMMMLLLLLLLK
.KDDDDDDKKKKKKKK
..KDDDDK........
..KKOOKK........
...KOOK.........
...KKKK.........
................
................
................
"""

ART["grenade_launcher"] = """
................
................
................
................
....KKKKKKKKKKK.
KK.KGGGGGGGGGGGK
KGKKGgggggggggGK
KGGKKKKGGGGGGGGK
KGGKDDDKKKKKKKK.
KKKKDMDDK.......
...KDDDDKK......
...KKKKKBK......
.......KKK......
................
................
................
"""

ART["rpg"] = """
................
................
................
..........KKK...
.........KgggK..
KKKKKKKKKgGGGgK.
KGGGGGGGGgGGGGGK
KgggggggggGGGGGK
KGGGGGGGGgGGGgK.
KKKKKDKKKKgggK..
....KDK..KKKK...
....KKK.........
................
................
................
................
"""

# Messer (diagonal wie Schwerter)
ART["kitchen_knife"] = """
................
................
.............KK.
............KHK.
...........KHLK.
..........KHLK..
.........KHLK...
........KHLK....
.......KHLK.....
......KKLK......
.....KWKK.......
....KWwK........
...KWwK.........
..KWwK..........
..KKK...........
................
"""

ART["combat_knife"] = """
................
.............KK.
............KHK.
...........KHLK.
..........KHLK..
.........KHLMK..
........KHLMK...
.......KHLMK....
.....KKKLMK.....
.....KDDKK......
......KBK.......
.....KBBK.......
....KBBK........
...KBBK.........
...KKK..........
................
"""

ART["machete"] = """
..........KKKK..
.........KHHLK..
........KHHLLK..
.......KHHLLK...
......KHHLLK....
.....KHHLLK.....
....KHHLLK......
...KHHLLK.......
...KHLLK........
..KKKKK.........
..KWK...........
.KWwK...........
.KWK............
.KKK............
................
................
"""

ART["karambit"] = """
................
................
................
..........KK....
.........KHK....
........KHLK....
.......KHLK.....
.......KHLK.....
......KHLK......
......KLKKKK....
.....KKKBBBK....
....KBBBKKBK....
....KBK..KKK....
....KKK.........
................
................
"""

# Munition
ART["ammo_9mm"] = """
................
................
................
................
....K...K...K...
...KLK.KLK.KLK..
...KMK.KMK.KMK..
..KYYYKYYYKYYYK.
..KYyYKYyYKYyYK.
..KYyYKYyYKYyYK.
..KyyyKyyyKyyyK.
..KKKKKKKKKKKKK.
................
................
................
................
"""

ART["ammo_556"] = """
................
.....K....K.....
....KLK..KLK....
....KMK..KMK....
....KYK..KYK....
...KYYYKKYYYK...
...KYyYKKYyYK...
...KYyYKKYyYK...
...KYyYKKYyYK...
...KYyYKKYyYK...
...KYyYKKYyYK...
...KyyyKKyyyK...
...KKKKKKKKKK...
................
................
................
"""

ART["shotgun_shell"] = """
................
................
................
...KKKK.KKKK....
...KrRK.KrRK....
...KrRK.KrRK....
...KrRK.KrRK....
...KrRK.KrRK....
...KrRK.KrRK....
...KrRK.KrRK....
...KYYK.KYYK....
...KyyK.KyyK....
...KKKK.KKKK....
................
................
................
"""

ART["ammo_50cal"] = """
.......KK.......
......KLLK......
......KMLK......
......KMMK......
.....KYYYYK.....
.....KYHYYK.....
.....KYHYyK.....
.....KYYYyK.....
.....KYYYyK.....
.....KYYYyK.....
.....KYYYyK.....
.....KYYYyK.....
....KKyyyyKK....
....KyyyyyyK....
....KKKKKKKK....
................
"""

ART["explosive_round"] = """
................
.......KK.......
......KgGK......
.....KgGGGK.....
.....KgGGGK.....
....KgGGGGGK....
....KRRRRRRK....
....KgGGGGGK....
....KYYYYYYK....
....KYyyyyyK....
.....KMMMMK.....
.....KDDDDK.....
.....KMDMDK.....
......KKKK......
................
................
"""

ART["antidote"] = """
................
......KKKK......
......KwwK......
......KwwK......
.......KK.......
......KHHK......
......KHHK......
.....KHEEEK.....
....KHEeEEEK....
...KHEeEEEEEK...
...KHEeEEEEEK...
...KEEEEEEEQK...
...KEEEEEEQQK...
....KQEEEQQK....
.....KKKKKK.....
................
"""


ART["grenade"] = """
................
................
.......KKK......
......KLLLK.....
......KKMKK.KK..
.....KKGGKKKLK..
....KGGgGGGKK...
...KGgGGGGGGK...
...KGGGGGGGGK...
...KGgGGGgGGK...
...KGGGGGGGGK...
...KGGgGGGGGK...
....KGGGGGGK....
.....KKKKKK.....
................
................
"""

ART["molotov"] = """
.......rO.......
......rOYr......
.......OY.......
.......KK.......
......KwwK......
......KwwK......
......KHHK......
.....KHOOOK.....
....KHOOOOOK....
...KHOyOOOOOK...
...KHOyOOOOOK...
...KOOOOOOOyK...
...KOOOOOOyyK...
....KyOOOyyK....
.....KKKKKK.....
................
"""

ART["bandage"] = """
................
................
................
....KKKKKKKK....
...KHHHHHHHHK...
..KHHHHHHHHHHK..
..KHHLHHHHLHHK..
..KHHHHRRHHHHK..
..KHHHRRRRHHHK..
..KHHHHRRHHHHK..
..KHHLHHHHLHHK..
..KHHHHHHHHHHK..
...KHHHHHHHHK...
....KKKKKKKK....
................
................
"""

ART["medkit"] = """
................
......KKKK......
......KDDK......
..KKKKKKKKKKKK..
..KrrrrrrrrrrK..
..KrrrrHHrrrrK..
..KrrrrHHrrrrK..
..KrrHHHHHHrrK..
..KrrHHHHHHrrK..
..KrrrrHHrrrrK..
..KrrrrHHrrrrK..
..KRRRRRRRRRRK..
..KRRRRRRRRRRK..
..KKKKKKKKKKKK..
................
................
"""

ART["immune_serum"] = """
................
.......KK.......
......KHHK......
......KMMK......
......KHHK......
.....KHSSK......
.....KHSSK......
.....KHSSK......
.....KHeSK......
.....KHSSK......
.....KHSSK......
.....KHSSK......
......KSK.......
.......K........
................
................
"""

ART["military_helmet"] = """
................
................
................
.....KKKKKK.....
....KGgGGgGK....
...KGGGgGGGGK...
...KgGGGGgGGK...
..KGGGGgGGGGGK..
..KGgGGGGGgGGK..
..KKKKKKKKKKKK..
..KK........KK..
..KK........KK..
................
................
................
................
"""

ART["military_vest"] = """
................
...KKK....KKK...
...KGK....KGK...
..KKGKKKKKKGKK..
..KGGGGGGGGGGK..
..KGgGKKKKGgGK..
..KGGGKMMKGGGK..
..KGgGKKKKGgGK..
..KGGGGGGGGGGK..
..KGKKGGGGKKGK..
..KGKMKGGKMKGK..
..KGKKGGGGKKGK..
..KGGGGGGGGGGK..
..KKKKKKKKKKKK..
................
................
"""

ART["military_pants"] = """
................
................
...KKKKKKKKKK...
...KDDDDYDDDK...
...KGGgGGGgGK...
...KGgGGgGGGK...
...KGGGKKGgGK...
...KGgGKKGGGK...
...KGGGKKGgGK...
...KGgGKKGGGK...
...KGGGKKGgGK...
...KGGGKKGGGK...
...KKKKKKKKKK...
................
................
................
"""

ART["military_boots"] = """
................
................
................
................
................
...KKKK..KKKK...
...KWWK..KWWK...
...KWWK..KWWK...
...KWWK..KWWK...
...KWWK..KWWK...
..KWWWK.KWWWK...
.KWWWWK.KWWWWK..
.KDDDDK.KDDDDK..
.KKKKKK.KKKKKK..
................
................
"""

ART["gas_mask"] = """
................
................
....KKKKKKKK....
...KDDDDDDDDK...
..KDDDDDDDDDDK..
..KDKKKDDKKKDK..
..KDKeeKKeeKDK..
..KDKeeKKeeKDK..
..KDDKKDDKKDDK..
..KDDDDMMDDDDK..
...KDDKMMKDDK...
....KKLLLLKK....
.....KLMMLK.....
.....KLMMLK.....
......KKKK......
................
"""

ART["nv_goggles"] = """
................
................
................
................
..KKKKKKKKKKKK..
.KDDDDDDDDDDDDK.
.KDKKKDDDDKKKDK.
.KKEEEKDDKEEEKK.
.KKEeEKKKKEeEKK.
.KKEEEK..KEEEKK.
..KKKK....KKKK..
................
................
................
................
................
"""

EGG = """
................
................
......KKKK......
.....KbbbbK.....
....KbbbbbbK....
....KbbsbbbK....
...KbbbbbbsbK...
...KbsbbbbbbK...
...KbbbbbsbbK...
..KbbbbbbbbbbK..
..KbbbsbbbbbbK..
..KbbbbbbbsbbK..
...KbbbbbbbbK...
....KbbbsbbK....
.....KKKKKK.....
................
"""

EGG_COLORS = {
    "walker": ("#6f8a4a", "#3b5f8f"),
    "runner": ("#a9a98a", "#9b1c1c"),
    "crawler": ("#9a9a8c", "#5e1414"),
    "bloater": ("#8e9a3c", "#d9e05a"),
    "spitter": ("#3f6a3a", "#8cff3a"),
    "brute": ("#6a5a6e", "#d0c8b8"),
    "screamer": ("#d8d4cc", "#101010"),
    "soldier": ("#4b5a2a", "#2e2a1c"),
    "leaper": ("#8a3a3a", "#e8e2d0"),
    "toxic": ("#d6b822", "#5a8a3a"),
    "patient_zero": ("#d8d0c4", "#8a0a0a"),
}

EFFECT = """
..................
......KKKKKK......
....KKEEEEEEKK....
...KEEeeeeeeEEK...
..KEeeKKeeKKeeEK..
..KEeKKKeeKKKeEK..
.KEeeKKKeeKKKeeEK.
.KEeeeeeeeeeeeeEK.
.KEeeeeeKKeeeeeEK.
.KEeeeeKKKKeeeeEK.
.KEEeeeeeeeeeeEEK.
..KEeKeKeKeKeeEK..
..KEeeeeeeeeeeEK..
...KEEeKeKeKEEK...
....KKEEEEEEKK....
......KKKKKK......
..................
..................
"""


def rows(art):
    return [r for r in art.strip("\n").split("\n")]


def save(img, folder, name):
    os.makedirs(folder, exist_ok=True)
    img.save(os.path.join(folder, name + ".png"))


def main():
    made = {}
    for name, art in ART.items():
        img = draw(rows(art))
        save(img, ITEM_DIR, name)
        made[name] = img
    for name, (base, spot) in EGG_COLORS.items():
        PALETTE["b"] = base
        PALETTE["s"] = spot
        img = draw(rows(EGG))
        save(img, ITEM_DIR, name + "_spawn_egg")
        made[name + "_spawn_egg"] = img
    eff = draw(rows(EFFECT), 18)
    save(eff, EFFECT_DIR, "infected")

    if PREVIEW:
        names = list(made)
        cols = 8
        sheet = Image.new("RGBA", (cols * 80, ((len(names) + cols - 1) // cols) * 80), (60, 60, 70, 255))
        for i, n in enumerate(names):
            big = made[n].resize((64, 64), Image.NEAREST)
            sheet.paste(big, ((i % cols) * 80 + 8, (i // cols) * 80 + 8), big)
        sheet.save(os.path.join(PREVIEW, "items_preview.png"))
    print("ok", len(made))


if __name__ == "__main__":
    main()
